In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cleaned_ecommerce_data.csv")

In [3]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_000001-1,CUST_00001,2023-05-29,40,Male,Ankara,Books,29.18,1,0.00,29.18,Digital Wallet,Mobile,14,9,True,13,4
1,ORD_000001-2,CUST_00001,2023-10-12,40,Male,Ankara,Home & Garden,644.40,1,138.05,506.35,Credit Card,Desktop,14,8,True,6,2
2,ORD_000001-3,CUST_00001,2023-12-05,40,Male,Ankara,Sports,332.82,5,0.00,1664.10,Credit Card,Mobile,15,10,True,9,4
3,ORD_000002-1,CUST_00002,2023-05-11,33,Male,Istanbul,Food,69.30,5,71.05,275.45,Digital Wallet,Desktop,16,13,True,4,4
4,ORD_000002-2,CUST_00002,2023-06-16,33,Male,Istanbul,Beauty,178.15,3,0.00,534.45,Credit Card,Mobile,14,7,True,6,4

In [4]:
df.tail()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
595,ORD_000181-7,CUST_00181,2024-03-20,42,Female,Ankara,Sports,192.57,4,0.00,770.28,Bank Transfer,Desktop,13,9,True,21,5
596,ORD_000182-1,CUST_00182,2023-02-04,24,Female,Istanbul,Home & Garden,736.16,3,0.00,2208.48,Digital Wallet,Mobile,18,10,True,8,4
597,ORD_000182-2,CUST_00182,2023-11-13,24,Female,Istanbul,Home & Garden,617.06,3,0.00,1851.18,Credit Card,Desktop,18,6,True,10,5
598,ORD_000182-3,CUST_00182,2024-01-04,24,Female,Istanbul,Beauty,190.18,4,0.00,760.72,Cash on Delivery,Mobile,16,7,True,9,4
599,ORD_000182-4,CUST_00182,2024-03-17,24,Female,Istanbul,Books,52.37,3,20.36,136.75,Debit Card,Desktop,10,9,True,4,2

In [5]:
df.shape

(600, 18)

In [6]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Date', 'Age', 'Gender', 'City',
       'Product_Category', 'Unit_Price', 'Quantity', 'Discount_Amount',
       'Total_Amount', 'Payment_Method', 'Device_Type',
       'Session_Duration_Minutes', 'Pages_Viewed', 'Is_Returning_Customer',
       'Delivery_Time_Days', 'Customer_Rating'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  600 non-null    str
 1   Customer_ID               600 non-null    str
 2   Date                      600 non-null    str
 3   Age                       600 non-null    int64
 4   Gender                    600 non-null    str
 5   City                      600 non-null    str
 6   Product_Category          600 non-null    str
 7   Unit_Price                600 non-null    float64
 8   Quantity                  600 non-null    int64
 9   Discount_Amount           600 non-null    float64
 10  Total_Amount              600 non-null    float64
 11  Payment_Method            600 non-null    str
 12  Device_Type               600 non-null    str
 13  Session_Duration_Minutes  600 non-null    int64
 14  Pages_Viewed              600 non-null    int64
 15  Is_Returning_Customer     600 non-null    bool
 16  Delivery_Time_Days        600 non-null    int64
 17  Customer_Rating           600 non-null    int64
dtypes: bool(1), float64(3), int64(6), str(8)
memory usage: 80.4 KB

In [8]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,600.000000,600.00000,600.000000,600.000000,600.000000,600.000000,600.000000,600.00000,600.000000
mean,34.841667,433.19085,3.026667,95.963800,1220.419400,14.456667,9.000000,6.61500,3.956667
std,10.738348,679.49726,1.390147,326.538629,2220.146437,2.960190,2.236441,3.43508,1.080154
min,18.000000,9.92000,1.000000,0.000000,19.950000,6.000000,3.000000,1.00000,1.000000
25%,27.000000,69.39000,2.000000,0.000000,160.740000,12.000000,7.000000,4.00000,3.000000
50%,35.000000,164.47000,3.000000,0.000000,422.675000,14.000000,9.000000,6.00000,4.000000
75%,42.000000,485.83750,4.000000,32.180000,1307.282500,17.000000,10.000000,9.00000,5.000000
max,67.000000,5677.63000,5.000000,2948.980000,20862.420000,23.000000,15.000000,21.00000,5.000000

In [9]:
df.isnull().sum()

Order_ID                    0
Customer_ID                 0
Date                        0
Age                         0
Gender                      0
City                        0
Product_Category            0
Unit_Price                  0
Quantity                    0
Discount_Amount             0
Total_Amount                0
Payment_Method              0
Device_Type                 0
Session_Duration_Minutes    0
Pages_Viewed                0
Is_Returning_Customer       0
Delivery_Time_Days          0
Customer_Rating             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [12]:
df.dtypes

Order_ID                        str
Customer_ID                     str
Date                            str
Age                           int64
Gender                          str
City                            str
Product_Category                str
Unit_Price                  float64
Quantity                      int64
Discount_Amount             float64
Total_Amount                float64
Payment_Method                  str
Device_Type                     str
Session_Duration_Minutes      int64
Pages_Viewed                  int64
Is_Returning_Customer          bool
Delivery_Time_Days            int64
Customer_Rating               int64
dtype: object

In [13]:
df["Date"] = pd.to_datetime(df["Date"])

In [14]:
df["Date"].head()

0   2023-05-29
1   2023-10-12
2   2023-12-05
3   2023-05-11
4   2023-06-16
Name: Date, dtype: datetime64[us]

In [15]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)

In [2]:
import os
print(os.getcwd())

C:\Users\HP